// @generated by scripts/gen-papi-config.ts. Do not edit.
// Default descriptor pair (DEFAULT_NETWORK = "paseo"), used when the
// #active-descriptors alias is not overridden (tsx, vue-tsc, tests).
export { mainDescriptor, bulletinDescriptor } from './paseo'
