// @generated by scripts/gen-papi-config.ts. Do not edit.
// Typed PAPI descriptor pair for the "paseo" network. Selected at
// build time via the #active-descriptors alias (see each SPA's nuxt.config.ts).
export {
  paseoAh as mainDescriptor,
  paseoBulletin as bulletinDescriptor,
} from '@polkadot-api/descriptors'
