// @generated by scripts/gen-papi-config.ts. Do not edit.
// Typed PAPI descriptor pair for the "previewnet" network. Selected at
// build time via the #active-descriptors alias (see each SPA's nuxt.config.ts).
export {
  previewnetAh as mainDescriptor,
  previewnetBulletin as bulletinDescriptor,
} from '@polkadot-api/descriptors'
