// @generated by scripts/gen-papi-config.ts. Do not edit.
// Typed PAPI descriptor pair for the "summit" network. Selected at
// build time via the #active-descriptors alias (see each SPA's nuxt.config.ts).
export {
  summitAh as mainDescriptor,
  summitBulletin as bulletinDescriptor,
} from '@polkadot-api/descriptors'
