/**
 * Generate PAPI config + descriptor re-exports from the network registry.
 *
 * Driven by the network registry in `packages/shared/host/networks.ts`. This
 * script derives, deterministically:
 *
 *   1. `packages/shared/.papi/polkadot-api.json`. One entry per chain that has
 *      a `descriptorKey`, keyed by that descriptor name. papi-managed fields
 *      (currently `codeHash`) are preserved from the existing file so this
 *      generator never fights `papi update`.
 *   2. `packages/shared/host/descriptors/<networkKey>.ts`. For each network
 *      whose main + bulletin chains both have a `descriptorKey`, a re-export of
 *      that network's descriptor pair as `mainDescriptor` / `bulletinDescriptor`.
 *   3. `packages/shared/host/descriptors/active.ts`. The DEFAULT_NETWORK pair,
 *      used when the build-time `#active-descriptors` alias isn't overridden
 *      (tsx, vue-tsc, tests).
 *
 * Chains without a `descriptorKey` are skipped. A network can be registered
 * (genesis/endpoints used for the runtime connection) before its typed
 * descriptor is wired up. Adding a descriptor for such a network: set its
 * `descriptorKey`, run `npm run papi:update` to fetch the `.scale`, commit both.
 *
 * Run via `npm run papi:config`. Output is committed; `postinstall` re-runs this
 * (then `papi` codegen) so a fresh checkout regenerates identically.
 */

import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import {
  readFileSync,
  writeFileSync,
  existsSync,
  readdirSync,
  unlinkSync,
  mkdirSync,
} from "node:fs";
import {
  NETWORKS,
  DEFAULT_NETWORK,
  type ChainEndpoint,
  type NetworkConfig,
} from "../../packages/shared/host/networks";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, "..", "..");
const sharedDir = resolve(repoRoot, "packages/shared");
const papiConfigPath = resolve(sharedDir, ".papi/polkadot-api.json");
const descriptorsDir = resolve(sharedDir, "host/descriptors");

/** Marker so we only ever prune/overwrite files this script owns. */
const GENERATED_MARKER = "@generated by scripts/gen-papi-config.ts";

interface PapiEntry {
  wsUrl: string;
  metadata: string;
  genesis?: string;
  /** Hash of the metadata, managed by `papi update`. Preserved across regen. */
  codeHash?: string;
}

interface PapiConfig {
  version: number;
  descriptorPath: string;
  entries: Record<string, PapiEntry>;
}

function readExistingConfig(): PapiConfig | null {
  if (!existsSync(papiConfigPath)) return null;
  try {
    return JSON.parse(readFileSync(papiConfigPath, "utf8")) as PapiConfig;
  } catch (e) {
    throw new Error(
      `Existing ${papiConfigPath} is not valid JSON: ${(e as Error).message}`,
    );
  }
}

/** Chains of a network, in stable order (main then bulletin), filtered to non-null. */
function chainsOf(network: NetworkConfig): ChainEndpoint[] {
  return [network.mainChain, network.bulletinChain].filter(
    (c): c is ChainEndpoint => c != null,
  );
}

function generateConfig(existing: PapiConfig | null): PapiConfig {
  const entries: Record<string, PapiEntry> = {};

  for (const network of Object.values(NETWORKS)) {
    for (const chain of chainsOf(network)) {
      if (!chain.descriptorKey) continue;
      const key = chain.descriptorKey;
      if (entries[key]) {
        throw new Error(
          `Duplicate descriptorKey "${key}" — descriptor keys must be unique across all chains.`,
        );
      }
      const prev = existing?.entries?.[key];
      const entry: PapiEntry = {
        wsUrl: chain.wsUrl,
        metadata: `.papi/metadata/${key}.scale`,
      };
      if (chain.genesisHash) entry.genesis = chain.genesisHash;
      // Preserve papi-managed metadata hash so regen produces no diff; only
      // `papi update` (fetching fresh metadata) legitimately changes it.
      if (prev?.codeHash) entry.codeHash = prev.codeHash;
      entries[key] = entry;
    }
  }

  return {
    version: existing?.version ?? 0,
    descriptorPath: existing?.descriptorPath ?? ".papi/descriptors",
    entries,
  };
}

/** Networks whose main + bulletin chains both expose a descriptorKey. */
function descriptorReadyNetworks(): Array<{
  key: string;
  main: string;
  bulletin: string;
}> {
  const ready: Array<{ key: string; main: string; bulletin: string }> = [];
  for (const network of Object.values(NETWORKS)) {
    const main = network.mainChain.descriptorKey;
    const bulletin = network.bulletinChain?.descriptorKey;
    if (main && bulletin) {
      ready.push({ key: network.key, main, bulletin });
    } else if (main || bulletin) {
      console.warn(
        `[gen-papi-config] Skipping descriptor re-export for "${network.key}": ` +
          `needs descriptorKey on BOTH main and bulletin chains (app requires both).`,
      );
    }
  }
  return ready;
}

function networkDescriptorFile(net: {
  key: string;
  main: string;
  bulletin: string;
}): string {
  return [
    `// ${GENERATED_MARKER}. Do not edit.`,
    `// Typed PAPI descriptor pair for the "${net.key}" network. Selected at`,
    `// build time via the #active-descriptors alias (see each SPA's nuxt.config.ts).`,
    `export {`,
    `  ${net.main} as mainDescriptor,`,
    `  ${net.bulletin} as bulletinDescriptor,`,
    `} from '@polkadot-api/descriptors'`,
    ``,
  ].join("\n");
}

function activeFile(defaultKey: string): string {
  return [
    `// ${GENERATED_MARKER}. Do not edit.`,
    `// Default descriptor pair (DEFAULT_NETWORK = "${defaultKey}"), used when the`,
    `// #active-descriptors alias is not overridden (tsx, vue-tsc, tests).`,
    `export { mainDescriptor, bulletinDescriptor } from './${defaultKey}'`,
    ``,
  ].join("\n");
}

/** Remove generated descriptor files no longer backed by a ready network. */
function pruneStaleDescriptorFiles(keep: Set<string>): void {
  if (!existsSync(descriptorsDir)) return;
  for (const name of readdirSync(descriptorsDir)) {
    if (!name.endsWith(".ts")) continue;
    if (keep.has(name)) continue;
    const full = resolve(descriptorsDir, name);
    const content = readFileSync(full, "utf8");
    if (content.includes(GENERATED_MARKER)) {
      unlinkSync(full);
      console.log(`[gen-papi-config] pruned stale ${name}`);
    }
  }
}

function writeIfChanged(path: string, content: string): boolean {
  const prev = existsSync(path) ? readFileSync(path, "utf8") : null;
  if (prev === content) return false;
  writeFileSync(path, content);
  return true;
}

function main(): void {
  // polkadot-api.json
  const existing = readExistingConfig();
  const config = generateConfig(existing);
  const configJson = JSON.stringify(config, null, 2) + "\n";
  const configChanged = writeIfChanged(papiConfigPath, configJson);

  // per-network descriptor re-exports
  mkdirSync(descriptorsDir, { recursive: true });
  const ready = descriptorReadyNetworks();
  const keep = new Set<string>(["active.ts"]);
  let filesChanged = 0;
  for (const net of ready) {
    const file = `${net.key}.ts`;
    keep.add(file);
    if (writeIfChanged(resolve(descriptorsDir, file), networkDescriptorFile(net))) {
      filesChanged++;
    }
  }

  // active.ts (default network)
  const defaultReady = ready.find((n) => n.key === DEFAULT_NETWORK);
  if (!defaultReady) {
    throw new Error(
      `DEFAULT_NETWORK "${DEFAULT_NETWORK}" has no descriptor pair — set descriptorKey ` +
        `on both its chains and run papi:update, or change DEFAULT_NETWORK.`,
    );
  }
  if (writeIfChanged(resolve(descriptorsDir, "active.ts"), activeFile(DEFAULT_NETWORK))) {
    filesChanged++;
  }

  pruneStaleDescriptorFiles(keep);

  console.log(
    `[gen-papi-config] ${Object.keys(config.entries).length} papi entries` +
      `${configChanged ? " (updated)" : " (unchanged)"}, ` +
      `${ready.length} descriptor re-exports${filesChanged ? ` (${filesChanged} updated)` : " (unchanged)"}.`,
  );
}

main();
